# NOTE: Il backend risponde su https://api.pyragogica.org:4000
# Ricordati di impostare su Netlify:
# VITE_API_URL = "https://api.pyragogica.org:4000"

[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"
# Redirect API calls to backend
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[functions."auth"]
  included_files = ["netlify/functions/auth.js"]

[functions."rag"]
  included_files = ["netlify/functions/rag.js"]

# Neon Database Configuration
[[plugins]]
  package = "@netlify/plugin-neon"

[context.production.environment]
  NEON_DATABASE_URL = "your-production-neon-url"
  FLOWISE_API_URL = "https://flowise.pyragogy.org/api/v1"
  FLOWISE_API_KEY = "your-flowise-api-key"

[context.deploy-preview.environment]
  NEON_DATABASE_URL = "your-preview-neon-url"
  FLOWISE_API_URL = "https://flowise.pyragogy.org/api/v1"
  FLOWISE_API_KEY = "your-flowise-api-key"

[context.branch-deploy.environment]
  NEON_DATABASE_URL = "your-branch-neon-url"
  FLOWISE_API_URL = "https://flowise.pyragogy.org/api/v1"
  FLOWISE_API_KEY = "your-flowise-api-key"
